-- StratScope demo seed data for the public marketing site.
-- Deterministic ids (demo-*) so the frontend and tests can rely on them.
-- Safe to re-run: uses INSERT OR IGNORE with fixed primary keys.

-- 1. Organization + project (dependency root for everything else)
INSERT OR IGNORE INTO organizations (id, name, slug, plan, settings, created_at, updated_at)
VALUES ('demo-org', 'StratScope Demo', 'stratscope-demo', 'pro', '{"demo":true}', datetime('now'), datetime('now'));

INSERT OR IGNORE INTO projects (id, organization_id, name, slug, environment, settings, created_at, updated_at)
VALUES ('demo-project-1', 'demo-org', 'Public Demo', 'public', 'production', '{"demo":true}', datetime('now'), datetime('now'));

-- 2. Agents
INSERT OR IGNORE INTO agents (id, project_id, name, description, framework, provider, model, version, config, created_at, updated_at)
VALUES
  ('demo-agent-1', 'demo-project-1', 'SEEA', 'StratScope Execution Evaluation Agent — runs evaluation traces on real agent executions', 'custom', 'groq', 'llama-3.3-70b-versatile', '2.1.0', '{"type":"evaluation","consent_opt_in":true}', datetime('now','-2 days'), datetime('now','-2 days')),
  ('demo-agent-2', 'demo-project-1', 'support-bot-v3', 'Customer support automation agent handling refunds, escalations and ticket triage', 'openai_sdk', 'openai', 'gpt-4o', '3.0.0', '{"type":"support","consent_opt_in":true}', datetime('now','-6 days'), datetime('now','-6 days')),
  ('demo-agent-3', 'demo-project-1', 'browser-agent-01', 'Browser automation agent for web research, form filling and screenshot capture', 'custom', 'anthropic', 'claude-3-5-sonnet', '1.4.2', '{"type":"browser","consent_opt_in":true}', datetime('now','-10 days'), datetime('now','-10 days'));

-- 3. Executions (12) — mixed statuses and models
INSERT OR IGNORE INTO executions (
  id, organization_id, project_id, agent_id, status, model, provider, trace_id,
  pipeline_version, sdk_version, started_at, completed_at, latency_ms,
  queue_latency_ms, processing_latency_ms, input_tokens, output_tokens, total_tokens,
  estimated_cost, input_ref, output_ref, metadata, error, created_at
)
VALUES
  ('demo-exec-1',  'demo-org', 'demo-project-1', 'demo-agent-1', 'completed', 'llama-3.3-70b-versatile',   'groq',      'trace-demo-001', '1.0', '0.9.0', strftime('%Y-%m-%dT%H:%M:%SZ','now','-5 minutes'), strftime('%Y-%m-%dT%H:%M:%SZ','now','-4 minutes'), 34210, 180, 34030, 1240, 862, 2102, 0.00121, 'r2://demo/exec-1-input.json', 'r2://demo/exec-1-output.json', '{"task":"evaluate_refund_trace","steps":4,"tools":["search_tickets","verify_auth","issue_refund","escalate_human"],"retries":1,"recovered":true}', NULL, strftime('%Y-%m-%dT%H:%M:%SZ','now','-5 minutes')),
  ('demo-exec-2',  'demo-org', 'demo-project-1', 'demo-agent-2', 'completed', 'gpt-4o',                     'openai',    'trace-demo-002', '1.0', '0.9.0', strftime('%Y-%m-%dT%H:%M:%SZ','now','-12 minutes'), strftime('%Y-%m-%dT%H:%M:%SZ','now','-11 minutes'), 18420, 95, 18325, 980, 421, 1401, 0.00283, 'r2://demo/exec-2-input.json', 'r2://demo/exec-2-output.json', '{"task":"process_refund","steps":6,"tools":["search_tickets","verify_auth","issue_refund"],"retries":0,"recovered":true}', NULL, strftime('%Y-%m-%dT%H:%M:%SZ','now','-12 minutes')),
  ('demo-exec-3',  'demo-org', 'demo-project-1', 'demo-agent-3', 'completed', 'claude-3-5-sonnet',          'anthropic', 'trace-demo-003', '1.1', '0.9.0', strftime('%Y-%m-%dT%H:%M:%SZ','now','-18 minutes'), strftime('%Y-%m-%dT%H:%M:%SZ','now','-17 minutes'), 52140, 140, 52000, 1820, 1410, 3230, 0.00412, 'r2://demo/exec-3-input.json', 'r2://demo/exec-3-output.json', '{"task":"research_competitor_pricing","steps":9,"tools":["navigate","extract","click","screenshot"],"retries":1,"recovered":true}', NULL, strftime('%Y-%m-%dT%H:%M:%SZ','now','-18 minutes')),
  ('demo-exec-4',  'demo-org', 'demo-project-1', 'demo-agent-2', 'failed',    'gpt-4o',                     'openai',    'trace-demo-004', '1.0', '0.9.0', strftime('%Y-%m-%dT%H:%M:%SZ','now','-25 minutes'), strftime('%Y-%m-%dT%H:%M:%SZ','now','-24 minutes'), 9310, 60, 9250, 740, 310, 1050, 0.00194, 'r2://demo/exec-4-input.json', NULL, '{"task":"ticket_triage","steps":3,"tools":["search_tickets","classify"],"retries":2,"recovered":false}', 'tool_timeout: search_tickets exceeded 30s budget after 2 retries', strftime('%Y-%m-%dT%H:%M:%SZ','now','-25 minutes')),
  ('demo-exec-5',  'demo-org', 'demo-project-1', 'demo-agent-1', 'running',   'llama-3.3-70b-versatile',   'groq',      'trace-demo-005', '1.1', '0.9.0', strftime('%Y-%m-%dT%H:%M:%SZ','now','-1 minutes'), NULL, 12840, 90, 12750, 410, 220, 630, 0.00034, 'r2://demo/exec-5-input.json', NULL, '{"task":"evaluate_browser_trace","steps":2,"tools":["parse_trace","score"],"retries":0,"recovered":true}', NULL, strftime('%Y-%m-%dT%H:%M:%SZ','now','-1 minutes')),
  ('demo-exec-6',  'demo-org', 'demo-project-1', 'demo-agent-3', 'completed', 'claude-3-5-sonnet',          'anthropic', 'trace-demo-006', '1.1', '0.9.0', strftime('%Y-%m-%dT%H:%M:%SZ','now','-40 minutes'), strftime('%Y-%m-%dT%H:%M:%SZ','now','-38 minutes'), 112300, 210, 112090, 3210, 2875, 6085, 0.00814, 'r2://demo/exec-6-input.json', 'r2://demo/exec-6-output.json', '{"task":"scrape_docs_site","steps":14,"tools":["navigate","extract","click","scroll"],"retries":2,"recovered":true}', NULL, strftime('%Y-%m-%dT%H:%M:%SZ','now','-40 minutes')),
  ('demo-exec-7',  'demo-org', 'demo-project-1', 'demo-agent-2', 'completed', 'gpt-4o',                     'openai',    'trace-demo-007', '1.0', '0.9.0', strftime('%Y-%m-%dT%H:%M:%SZ','now','-55 minutes'), strftime('%Y-%m-%dT%H:%M:%SZ','now','-54 minutes'), 22140, 80, 22060, 1130, 640, 1770, 0.00321, 'r2://demo/exec-7-input.json', 'r2://demo/exec-7-output.json', '{"task":"escalate_ticket","steps":5,"tools":["search_tickets","verify_auth","escalate_human"],"retries":0,"recovered":true}', NULL, strftime('%Y-%m-%dT%H:%M:%SZ','now','-55 minutes')),
  ('demo-exec-8',  'demo-org', 'demo-project-1', 'demo-agent-1', 'completed', 'llama-3.3-70b-versatile',   'groq',      'trace-demo-008', '1.0', '0.9.0', strftime('%Y-%m-%dT%H:%M:%SZ','now','-70 minutes'), strftime('%Y-%m-%dT%H:%M:%SZ','now','-69 minutes'), 15670, 120, 15550, 890, 410, 1300, 0.00071, 'r2://demo/exec-8-input.json', 'r2://demo/exec-8-output.json', '{"task":"score_recovery_strategy","steps":4,"tools":["parse_trace","score"],"retries":0,"recovered":true}', NULL, strftime('%Y-%m-%dT%H:%M:%SZ','now','-70 minutes')),
  ('demo-exec-9',  'demo-org', 'demo-project-1', 'demo-agent-3', 'failed',    'claude-3-5-sonnet',          'anthropic', 'trace-demo-009', '1.1', '0.9.0', strftime('%Y-%m-%dT%H:%M:%SZ','now','-95 minutes'), strftime('%Y-%m-%dT%H:%M:%SZ','now','-93 minutes'), 74200, 160, 74040, 2410, 1680, 4090, 0.00547, 'r2://demo/exec-9-input.json', NULL, '{"task":"login_to_dashboard","steps":7,"tools":["navigate","type","click","screenshot"],"retries":3,"recovered":false}', 'auth_error: 2FA challenge not handled, session expired', strftime('%Y-%m-%dT%H:%M:%SZ','now','-95 minutes')),
  ('demo-exec-10', 'demo-org', 'demo-project-1', 'demo-agent-2', 'cancelled', 'gpt-4o',                     'openai',    'trace-demo-010', '1.0', '0.9.0', strftime('%Y-%m-%dT%H:%M:%SZ','now','-120 minutes'), strftime('%Y-%m-%dT%H:%M:%SZ','now','-119 minutes'), 12340, 70, 12270, 620, 280, 900, 0.00152, 'r2://demo/exec-10-input.json', NULL, '{"task":"batch_email_digest","steps":2,"tools":["search_tickets"],"retries":0,"recovered":false}', 'cancelled_by_operator: duplicate batch job already running', strftime('%Y-%m-%dT%H:%M:%SZ','now','-120 minutes')),
  ('demo-exec-11', 'demo-org', 'demo-project-1', 'demo-agent-1', 'completed', 'llama-3.3-70b-versatile',   'groq',      'trace-demo-011', '1.1', '0.9.0', strftime('%Y-%m-%dT%H:%M:%SZ','now','-150 minutes'), strftime('%Y-%m-%dT%H:%M:%SZ','now','-149 minutes'), 4210, 40, 4170, 240, 130, 370, 0.00021, 'r2://demo/exec-11-input.json', 'r2://demo/exec-11-output.json', '{"task":"health_check","steps":2,"tools":["ping","report"],"retries":0,"recovered":true}', NULL, strftime('%Y-%m-%dT%H:%M:%SZ','now','-150 minutes')),
  ('demo-exec-12', 'demo-org', 'demo-project-1', 'demo-agent-3', 'completed', 'gpt-4o',                     'openai',    'trace-demo-012', '1.0', '0.9.0', strftime('%Y-%m-%dT%H:%M:%SZ','now','-200 minutes'), strftime('%Y-%m-%dT%H:%M:%SZ','now','-198 minutes'), 41210, 110, 41100, 1540, 980, 2520, 0.00468, 'r2://demo/exec-12-input.json', 'r2://demo/exec-12-output.json', '{"task":"fill_lead_form","steps":8,"tools":["navigate","type","click","extract"],"retries":1,"recovered":true}', NULL, strftime('%Y-%m-%dT%H:%M:%SZ','now','-200 minutes'));

-- 4. Events (20) — spread across the sample executions
INSERT OR IGNORE INTO events (id, execution_id, event_type, service, payload, metadata, timestamp, schema_version)
VALUES
  ('demo-event-01',  'demo-exec-1',  'execution.completed', 'execution',   '{"status":"completed","latency_ms":34210,"cost_usd":0.00121}', '{"trace_id":"trace-demo-001"}', strftime('%Y-%m-%dT%H:%M:%SZ','now','-4 minutes'),  '1.0'),
  ('demo-event-02',  'demo-exec-1',  'tool.executed',       'execution',   '{"tool":"search_tickets","status":"ok","latency_ms":312}',       '{"trace_id":"trace-demo-001"}', strftime('%Y-%m-%dT%H:%M:%SZ','now','-5 minutes'),  '1.0'),
  ('demo-event-03',  'demo-exec-1',  'decision.made',       'execution',   '{"decision":"retry_tool","reason":"issue_refund_timeout"}',       '{"trace_id":"trace-demo-001"}', strftime('%Y-%m-%dT%H:%M:%SZ','now','-4 minutes'),  '1.0'),
  ('demo-event-04',  'demo-exec-2',  'execution.completed', 'execution',   '{"status":"completed","latency_ms":18420,"cost_usd":0.00283}',   '{"trace_id":"trace-demo-002"}', strftime('%Y-%m-%dT%H:%M:%SZ','now','-11 minutes'), '1.0'),
  ('demo-event-05',  'demo-exec-2',  'tool.executed',       'execution',   '{"tool":"issue_refund","status":"ok","latency_ms":1204}',         '{"trace_id":"trace-demo-002"}', strftime('%Y-%m-%dT%H:%M:%SZ','now','-11 minutes'), '1.0'),
  ('demo-event-06',  'demo-exec-3',  'execution.completed', 'execution',   '{"status":"completed","latency_ms":52140,"cost_usd":0.00412}',   '{"trace_id":"trace-demo-003"}', strftime('%Y-%m-%dT%H:%M:%SZ','now','-17 minutes'), '1.0'),
  ('demo-event-07',  'demo-exec-3',  'decision.made',       'execution',   '{"decision":"proceed","reason":"pricing_data_extracted"}',        '{"trace_id":"trace-demo-003"}', strftime('%Y-%m-%dT%H:%M:%SZ','now','-17 minutes'), '1.0'),
  ('demo-event-08',  'demo-exec-4',  'failure.recorded',    'execution',   '{"error":"tool_timeout","tool":"search_tickets","retries":2}',    '{"trace_id":"trace-demo-004"}', strftime('%Y-%m-%dT%H:%M:%SZ','now','-24 minutes'), '1.0'),
  ('demo-event-09',  'demo-exec-4',  'execution.completed', 'execution',   '{"status":"failed","latency_ms":9310,"cost_usd":0.00194}',       '{"trace_id":"trace-demo-004"}', strftime('%Y-%m-%dT%H:%M:%SZ','now','-24 minutes'), '1.0'),
  ('demo-event-10',  'demo-exec-5',  'execution.completed', 'execution',   '{"status":"running","latency_ms":12840,"cost_usd":0.00034}',     '{"trace_id":"trace-demo-005"}', strftime('%Y-%m-%dT%H:%M:%SZ','now','-1 minutes'),  '1.0'),
  ('demo-event-11',  'demo-exec-5',  'tool.executed',       'execution',   '{"tool":"parse_trace","status":"ok","latency_ms":890}',           '{"trace_id":"trace-demo-005"}', strftime('%Y-%m-%dT%H:%M:%SZ','now','-1 minutes'),  '1.0'),
  ('demo-event-12',  'demo-exec-6',  'execution.completed', 'execution',   '{"status":"completed","latency_ms":112300,"cost_usd":0.00814}',  '{"trace_id":"trace-demo-006"}', strftime('%Y-%m-%dT%H:%M:%SZ','now','-38 minutes'), '1.0'),
  ('demo-event-13',  'demo-exec-6',  'tool.executed',       'execution',   '{"tool":"extract","status":"ok","latency_ms":1240}',              '{"trace_id":"trace-demo-006"}', strftime('%Y-%m-%dT%H:%M:%SZ','now','-39 minutes'), '1.0'),
  ('demo-event-14',  'demo-exec-7',  'execution.completed', 'execution',   '{"status":"completed","latency_ms":22140,"cost_usd":0.00321}',   '{"trace_id":"trace-demo-007"}', strftime('%Y-%m-%dT%H:%M:%SZ','now','-54 minutes'), '1.0'),
  ('demo-event-15',  'demo-exec-7',  'decision.made',       'execution',   '{"decision":"escalate","reason":"refund_exceeds_limit"}',         '{"trace_id":"trace-demo-007"}', strftime('%Y-%m-%dT%H:%M:%SZ','now','-54 minutes'), '1.0'),
  ('demo-event-16',  'demo-exec-8',  'execution.completed', 'execution',   '{"status":"completed","latency_ms":15670,"cost_usd":0.00071}',   '{"trace_id":"trace-demo-008"}', strftime('%Y-%m-%dT%H:%M:%SZ','now','-69 minutes'), '1.0'),
  ('demo-event-17',  'demo-exec-9',  'failure.recorded',    'execution',   '{"error":"auth_error","detail":"2FA challenge not handled"}',     '{"trace_id":"trace-demo-009"}', strftime('%Y-%m-%dT%H:%M:%SZ','now','-93 minutes'), '1.0'),
  ('demo-event-18',  'demo-exec-9',  'execution.completed', 'execution',   '{"status":"failed","latency_ms":74200,"cost_usd":0.00547}',      '{"trace_id":"trace-demo-009"}', strftime('%Y-%m-%dT%H:%M:%SZ','now','-93 minutes'), '1.0'),
  ('demo-event-19',  'demo-exec-11', 'execution.completed', 'execution',   '{"status":"completed","latency_ms":4210,"cost_usd":0.00021}',    '{"trace_id":"trace-demo-011"}', strftime('%Y-%m-%dT%H:%M:%SZ','now','-149 minutes'),'1.0'),
  ('demo-event-20',  'demo-exec-12', 'tool.executed',       'execution',   '{"tool":"fill_form","status":"ok","latency_ms":2100}',            '{"trace_id":"trace-demo-012"}', strftime('%Y-%m-%dT%H:%M:%SZ','now','-199 minutes'),'1.0');

-- 5. Datasets (4)
INSERT OR IGNORE INTO datasets (
  id, organization_id, project_id, name, description, category, status, version,
  parent_dataset_id, record_count, schema_definition, filters, tags, export_formats,
  storage_path, checksum, metadata, created_at, updated_at
)
VALUES
  ('demo-dataset-1', 'demo-org', 'demo-project-1', 'Agent Failure Corpus — Q3', 'Real failure executions across support, browser and evaluation agents: tool timeouts, auth errors and recovery attempts.', 'failure', 'ready', 1, NULL, 1240, '{"fields":["execution_id","error","tool","retries","recovery","cost_usd"]}', '{"status":["failed"]}', '["failure","support","browser"]', '["jsonl","csv","parquet"]', 'r2://demo/datasets/failure-corpus-q3.jsonl', 'sha256:8f3a2c9d', '{"source":"production_traces","version":"1.0.0"}', strftime('%Y-%m-%dT%H:%M:%SZ','now','-3 days'), strftime('%Y-%m-%dT%H:%M:%SZ','now','-3 days')),
  ('demo-dataset-2', 'demo-org', 'demo-project-1', 'Tool Selection Traces', 'Tool call sequences with outcomes: which sequences succeed, which fall back, and the context around each choice.', 'tool_selection', 'ready', 1, NULL, 3620, '{"fields":["execution_id","tool_sequence","decisions","outcome"]}', '{"agent_id":["demo-agent-2","demo-agent-3"]}', '["tool-use","routing"]', '["jsonl","csv"]', 'r2://demo/datasets/tool-selection-traces.jsonl', 'sha256:9b1e77da', '{"source":"production_traces","version":"1.0.0"}', strftime('%Y-%m-%dT%H:%M:%SZ','now','-5 days'), strftime('%Y-%m-%dT%H:%M:%SZ','now','-5 days')),
  ('demo-dataset-3', 'demo-org', 'demo-project-1', 'Multi-Step Reasoning Traces', 'Long-horizon reasoning traces from browser agents: planning, branching, dead-ends and recovered paths.', 'reasoning', 'validating', 1, NULL, 890, '{"fields":["execution_id","plan","steps","recoveries"]}', '{"agent_id":["demo-agent-3"]}', '["reasoning","browser"]', '["jsonl","csv"]', 'r2://demo/datasets/reasoning-traces.jsonl', 'sha256:2f4c8e51', '{"source":"production_traces","version":"0.9.0"}', strftime('%Y-%m-%dT%H:%M:%SZ','now','-7 days'), strftime('%Y-%m-%dT%H:%M:%SZ','now','-7 days')),
  ('demo-dataset-4', 'demo-org', 'demo-project-1', 'Coding Agent Evaluations', 'Evaluated coding executions with pass/fail verdicts, patch quality scores and failure mode annotations.', 'coding', 'ready', 1, NULL, 540, '{"fields":["execution_id","verdict","quality_score","failure_modes"]}', '{"category":["coding"]}', '["coding","evaluation"]', '["jsonl","csv","parquet"]', 'r2://demo/datasets/coding-evaluations.jsonl', 'sha256:5a1d0f7b', '{"source":"evaluation_pipeline","version":"1.0.0"}', strftime('%Y-%m-%dT%H:%M:%SZ','now','-9 days'), strftime('%Y-%m-%dT%H:%M:%SZ','now','-9 days'));

-- 6. Dataset versions (one per dataset)
INSERT OR IGNORE INTO dataset_versions (
  id, dataset_id, organization_id, version, record_count, schema_definition, storage_path,
  checksum, change_summary, metadata, status, filters, created_at, updated_at
)
VALUES
  ('demo-dsv-1', 'demo-dataset-1', 'demo-org', 1, 1240, '{"fields":["execution_id","error","tool","retries","recovery","cost_usd"]}', 'r2://demo/datasets/failure-corpus-q3.jsonl', 'sha256:8f3a2c9d', 'Initial failure corpus build', '{"records":1240,"sources":3}', 'ready', '{"status":["failed"]}', strftime('%Y-%m-%dT%H:%M:%SZ','now','-3 days'), strftime('%Y-%m-%dT%H:%M:%SZ','now','-3 days')),
  ('demo-dsv-2', 'demo-dataset-2', 'demo-org', 1, 3620, '{"fields":["execution_id","tool_sequence","decisions","outcome"]}', 'r2://demo/datasets/tool-selection-traces.jsonl', 'sha256:9b1e77da', 'Initial tool selection build', '{"records":3620,"sources":2}', 'ready', '{"agent_id":["demo-agent-2","demo-agent-3"]}', strftime('%Y-%m-%dT%H:%M:%SZ','now','-5 days'), strftime('%Y-%m-%dT%H:%M:%SZ','now','-5 days')),
  ('demo-dsv-3', 'demo-dataset-3', 'demo-org', 1, 890, '{"fields":["execution_id","plan","steps","recoveries"]}', 'r2://demo/datasets/reasoning-traces.jsonl', 'sha256:2f4c8e51', 'Initial reasoning traces build', '{"records":890,"sources":1}', 'validating', '{"agent_id":["demo-agent-3"]}', strftime('%Y-%m-%dT%H:%M:%SZ','now','-7 days'), strftime('%Y-%m-%dT%H:%M:%SZ','now','-7 days')),
  ('demo-dsv-4', 'demo-dataset-4', 'demo-org', 1, 540, '{"fields":["execution_id","verdict","quality_score","failure_modes"]}', 'r2://demo/datasets/coding-evaluations.jsonl', 'sha256:5a1d0f7b', 'Initial coding evaluations build', '{"records":540,"sources":1}', 'ready', '{"category":["coding"]}', strftime('%Y-%m-%dT%H:%M:%SZ','now','-9 days'), strftime('%Y-%m-%dT%H:%M:%SZ','now','-9 days'));

-- 7. Benchmarks (3)
INSERT OR IGNORE INTO benchmarks (
  id, organization_id, project_id, name, description, benchmark_type, status, entries,
  dataset_id, config, results, started_at, completed_at, created_at, updated_at
)
VALUES
  ('demo-bench-1', 'demo-org', 'demo-project-1', 'LLM Success Rate — Support Tasks', 'Success rate of gpt-4o vs llama-3.3-70b on support executions, measured on real production traces.', 'model_comparison', 'completed', '[{"model":"gpt-4o","count":620},{"model":"llama-3.3-70b-versatile","count":580}]', 'demo-dataset-1', '{"metrics":["success_rate","latency_p50"]}', '{"gpt-4o":{"success_rate":0.92,"latency_p50_ms":18420},"llama-3.3-70b-versatile":{"success_rate":0.87,"latency_p50_ms":34210}}', strftime('%Y-%m-%dT%H:%M:%SZ','now','-2 days'), strftime('%Y-%m-%dT%H:%M:%SZ','now','-2 days'), strftime('%Y-%m-%dT%H:%M:%SZ','now','-2 days'), strftime('%Y-%m-%dT%H:%M:%SZ','now','-2 days')),
  ('demo-bench-2', 'demo-org', 'demo-project-1', 'Browser Agent Recovery Benchmark', 'Recovery quality of browser-agent-01: how often it recovers from dead-ends and timeouts without human intervention.', 'success_rate', 'completed', '[{"agent":"browser-agent-01","runs":890}]', 'demo-dataset-3', '{"metrics":["recovery_rate","dead_end_rate"]}', '{"browser-agent-01":{"recovery_rate":0.78,"dead_end_rate":0.14}}', strftime('%Y-%m-%dT%H:%M:%SZ','now','-4 days'), strftime('%Y-%m-%dT%H:%M:%SZ','now','-4 days'), strftime('%Y-%m-%dT%H:%M:%SZ','now','-4 days'), strftime('%Y-%m-%dT%H:%M:%SZ','now','-4 days')),
  ('demo-bench-3', 'demo-org', 'demo-project-1', 'Cost per Execution — Agent Comparison', 'Average cost per completed execution across support-bot-v3, browser-agent-01 and SEEA.', 'cost_comparison', 'draft', '[{"agent":"support-bot-v3"},{"agent":"browser-agent-01"},{"agent":"SEEA"}]', 'demo-dataset-2', '{"metrics":["avg_cost_usd","p95_cost_usd"]}', NULL, NULL, NULL, strftime('%Y-%m-%dT%H:%M:%SZ','now','-1 days'), strftime('%Y-%m-%dT%H:%M:%SZ','now','-1 days'));
